
apiVersion: v1
kind: Service
metadata:
  name: users-api-svc
  namespace: backend-api
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30001
  selector:
    app: users-api
